#!/bin/bash

files=(./*)
dockerfiles=()
for ((i=0; i<${#files[@]}; i++)); do
	if [[ "${files[$i]}" == *.dockerfile ]]; then
		dockerfiles+=("${files[$i]}")
	fi
done

printf "We're going to build a docker container!\n"
printf "Please select a container: \n"

for ((i=0; i<${#dockerfiles[@]}; i++)); do
	printf "\t%-2s ${dockerfiles[$i]}\n" $i;
done

printf "\n> "
read file_num

if [[ $file_num == "q" ]]; then
	return 0
fi

chosen_file="${dockerfiles[$file_num]}"
printf "You chose: $chosen_file\n\n"

printf "please enter the image name to use:\n> "
read name

docker build -t $name -f $chosen_file .
